spring:
  freemarker:
    charset: UTF-8
  profiles:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.96.156.242:3306/myspringboot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: Mysql123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  config: classpath:logging-config.xml

snmp:
  ip: 10.96.156.242
  port: 162