server:
  servlet:
  port: 443
  ssl:
    key-store: classpath:pfx/www.zghuang.top.pfx
    key-alias: alias
    enabled: true
    key-store-password: 2z0tihGH
    key-store-type: PKCS12
http:
  port: 80
condition:
  http2https: true
spring:
  freemarker:
    charset: UTF-8
  profiles:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/myspringboot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: Mysql123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: 192.168.0.228
    port: 6379
    password: Myredis123
    database: 0
    timeout: 10s

  rabbitmq:
    host: 192.168.0.228
    port: 5672
    username: root
    password: root1234
    virtual-host: /
    publisher-confirms: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: com.kafka.consumer.zhigang
      auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: 192.168.0.228:9092
    topic:
      name: mytopic
      numPartitions: 2
      replicationFactor: 2

zookeeper:
  baseSleepTimeMs: 100
  maxRetries: 100
  server: 192.168.0.228
  sessionTimeoutMs: 100
  connectionTimeoutMs: 100
  namespace: zookeepertest
  digest: tttt

logging:
  config: classpath:logging-config.xml

snmp:
  ip: 127.0.0.1
  port: 162