
package com.zhigang.myspringboot.domain.alarmws;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotifyAlarmSyncPortService", targetNamespace = "http://www.ctsi.com.cn/webservices/service", wsdlLocation = "http://10.96.155.163:8080/fums/ws/notifyAlarmSync/alarmSync.wsdl")
public class NotifyAlarmSyncPortService
    extends Service
{

    private final static URL NOTIFYALARMSYNCPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException NOTIFYALARMSYNCPORTSERVICE_EXCEPTION;
    private final static QName NOTIFYALARMSYNCPORTSERVICE_QNAME = new QName("http://www.ctsi.com.cn/webservices/service", "NotifyAlarmSyncPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.96.155.163:8080/fums/ws/notifyAlarmSync/alarmSync.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTIFYALARMSYNCPORTSERVICE_WSDL_LOCATION = url;
        NOTIFYALARMSYNCPORTSERVICE_EXCEPTION = e;
    }

    public NotifyAlarmSyncPortService() {
        super(__getWsdlLocation(), NOTIFYALARMSYNCPORTSERVICE_QNAME);
    }

    public NotifyAlarmSyncPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTIFYALARMSYNCPORTSERVICE_QNAME, features);
    }

    public NotifyAlarmSyncPortService(URL wsdlLocation) {
        super(wsdlLocation, NOTIFYALARMSYNCPORTSERVICE_QNAME);
    }

    public NotifyAlarmSyncPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTIFYALARMSYNCPORTSERVICE_QNAME, features);
    }

    public NotifyAlarmSyncPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotifyAlarmSyncPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NotifyAlarmSyncPort
     */
    @WebEndpoint(name = "NotifyAlarmSyncPortSoap11")
    public NotifyAlarmSyncPort getNotifyAlarmSyncPortSoap11() {
        return super.getPort(new QName("http://www.ctsi.com.cn/webservices/service", "NotifyAlarmSyncPortSoap11"), NotifyAlarmSyncPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotifyAlarmSyncPort
     */
    @WebEndpoint(name = "NotifyAlarmSyncPortSoap11")
    public NotifyAlarmSyncPort getNotifyAlarmSyncPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ctsi.com.cn/webservices/service", "NotifyAlarmSyncPortSoap11"), NotifyAlarmSyncPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTIFYALARMSYNCPORTSERVICE_EXCEPTION!= null) {
            throw NOTIFYALARMSYNCPORTSERVICE_EXCEPTION;
        }
        return NOTIFYALARMSYNCPORTSERVICE_WSDL_LOCATION;
    }

}
